# PII regex patterns configuration (full coverage)
ip_address:
  - pattern: "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"
password:
  - pattern: "(?i)(?:password|passwd|pwd)[\\s:=\"']+[^\\s\"'\\n]+"
  - pattern: "(?i)(?:password|passwd|pwd)\\s+is\\s+[^\\s\"'\\n]+"
  - pattern: "(?i)(?:паролем|пароль)[\\s:=\"']+[^\\s\"'\\n]+"
  - pattern: "(?i)(?:паролем|пароль)\\s+[A-Za-z0-9!@#$%^&*()_+\\-=\\[\\]{}|;':\",./<>?]{8,}\\b"
api_key:
  - pattern: "(?i)(?:api[_-]?key|access[_-]?key|secret[_-]?key|token)[\\s:=\"']+[^\\s\"'\\n]+"
connection_string:
  - pattern: "(?i)(?:(?:connection[_-]?string|conn[_-]?str)[\\s:=\"']+[^\\n]+|(?:mongodb|postgresql|mysql|jdbc|redis)://[^\\s\"'\\n]+)"
private_key:
  - pattern: "(?i)(?:private[_-]?key|secret[_-]?key)[\\s:=\"']+[^\\n]+?(?:-----END|[\\s\"']|$)"
jwt_token:
  - pattern: "(?i)(?:jwt|token|bearer)[\\s:=\"']+[A-Za-z0-9-_\\.]+"
aws_key:
  - pattern: "(?i)(?:aws[_-]?(?:secret|access)[_-]?key)[\\s:=\"']+[^\\s\"'\\n]+"
  - pattern: "AKIA[0-9A-Z]{16,20}"
stripe_key:
  - pattern: "(?i)sk_live_[0-9a-zA-Z]+"
sendgrid_key:
  - pattern: "SG\\.[A-Za-z0-9_-]{22}\\.[A-Za-z0-9_-]{43}" 